# Generated by Django 5.2.1 on 2026-01-15 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='APagar',
            fields=[
                ('idcontapagar', models.AutoField(primary_key=True, serialize=False)),
                ('descricao', models.CharField(max_length=30)),
                ('valorparcela', models.DecimalField(decimal_places=2, max_digits=15)),
                ('numeroparcela', models.IntegerField()),
                ('datavencimento', models.DateField()),
                ('dataquitacao', models.DateField(blank=True, null=True)),
                ('valordesconto', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('valorjuros', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
            ],
            options={
                'db_table': 'a_pagar',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AReceber',
            fields=[
                ('idconta', models.AutoField(primary_key=True, serialize=False)),
                ('descricao', models.CharField(max_length=30)),
                ('valorparcela', models.DecimalField(decimal_places=2, max_digits=15)),
                ('numeroparcela', models.IntegerField()),
                ('datavencimento', models.DateField()),
                ('dataquitacao', models.DateField(blank=True, null=True)),
                ('valordesconto', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('valorjuros', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
            ],
            options={
                'db_table': 'a_receber',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PlanoDeContas',
            fields=[
                ('idplanocontas', models.AutoField(primary_key=True, serialize=False)),
                ('descricao', models.CharField(blank=True, max_length=30, null=True)),
                ('tipofluxocaixa', models.SmallIntegerField(blank=True, null=True)),
                ('conta', models.CharField(blank=True, max_length=15, null=True)),
            ],
            options={
                'db_table': 'plano_de_contas',
                'managed': False,
            },
        ),
    ]
