# Generated by Django 5.2.1 on 2026-01-15 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_usuario_telefone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='telefone',
        ),
    ]
